import Image from "next/image";
import localFont from 'next/font/local'
import "./globals.css";

import brandLogo from "../../public/ares.svg";
import iconLang from "../../public/language.svg";
import iconDropdown from "../../public/dropdown.svg";
import Header from "./components/molecules/header";
import Footer from "./components/molecules/footer";

const Gilmer = localFont({
  src: [
    {
      path: '../../public/Gilmer-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/Gilmer-Medium.woff2',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../../public/Gilmer-Regular.woff2',
      weight: '400',
      style: 'normal',
    }
  ],
  display: 'swap',
  variable: '--font-gilmer',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Gilmer.variable} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
